title: Zach Starkebaum
email: zach@relevantwalk.com
description: >
baseurl: ""
url: "http://rebelzach.github.io"
twitter_username: rebelzach
github_username:  rebelzach

# Build settings
markdown: kramdown

collections:
- portfolio_items
